/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  m-alwan
 * Created: Nov 12, 2017
 */

CREATE TABLE "LOCATION"

(    
   "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1), 
    "CITY" VARCHAR(200) NOT NULL
 ); 
  CREATE TABLE "COURSE"

(    
   "CODE" VARCHAR(200) NOT NULL PRIMARY KEY, 
    "TITLE" VARCHAR(500) NOT NULL
 ); 
 CREATE TABLE "COURSE_SESSION"

(    
   "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1), 
    "START_DATE"    DATE NOT NULL,
    "END_DATE"      DATE NOT NULL,
    "COURSE_CODE"   VARCHAR(200) NOT NULL,
    "LOCATION_ID"   INT NOT NULL 
 ); 
CREATE TABLE "CLIENT"

(    
   "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1), 
    "LASTNAME"          VARCHAR(200) NOT NULL,
    "FIRSTNAME"         VARCHAR(200) NOT NULL,
    "ADDRESS"           VARCHAR(200) NOT NULL,
    "PHONE"             VARCHAR(200) NOT NULL,
    "EMAIL"             VARCHAR(200) NOT NULL ,
    "COURSE_SESSION_ID" INT NOT NULL  
 ); 
ALTER TABLE "COURSE_SESSION"
ADD CONSTRAINT  "FK_COURSE_CODE"
FOREIGN KEY (COURSE_CODE)
REFERENCES COURSE (CODE);

ALTER TABLE "COURSE_SESSION"
ADD CONSTRAINT  "FK_LOCATION_ID"
FOREIGN KEY (LOCATION_ID)
REFERENCES LOCATION (ID);

ALTER TABLE "CLIENT"
ADD CONSTRAINT  "FK_COURSE_SESSION_ID"
FOREIGN KEY (COURSE_SESSION_ID)
REFERENCES COURSE_SESSION (ID);
